.literature {
  width: 60%;
  margin-left:20%;
  margin-top: 3em;
  margin-bottom: 3em;
}

img{
  display: block;
  margin:0;
  padding:0;
  text-align: center;
  line-height: 0;
}

figure > img {
  display: inline;
}
footer > img {
  display: inline;
}


figure{
  margin:0;
  padding:0;
  text-align: center;
}


figure >figcaption{
  font-size: 0.9em;
}

.ref {
    color: #de644b;
    text-decoration: none;
    outline:0;
}

.audio{
  display: block;
  background: #f1f3f4;
  padding-left: 10%;
  padding-right: 10%;
  padding-top: 20px;
  padding-bottom: 12px;

}

audio{
  display: inline;
  width: 100%;
  outline:0;
}


body {
  background-color: #FFF;
  font-family: 'roboto',sans-serif;
  font-size: 1.2em;
  line-height: 1.5;
  font-weight: 300;
  margin:0;
}
h1 {
  color: black;
  font-weight: 500;
  font-size: 2em;
  text-align: center;
}
h2 {
  color: black;
  font-weight: 500;
  font-size: 1.4em;
  margin-top: 2em;
}
h3 {
  color: black;
  font-weight: 500;
}
p {
  color: black;
  font-weight: 300;
}


.details{
  display: block;
  border-bottom: 1px solid #BBB;
}

details{
  background-color: #E9E9E9;
}


details[open]{
  padding-bottom: 4em;
  background-color: #F0F0F0;
}


details > p {
  padding-left: 10%;
  padding-right: 10%;
}

details > summary {
  display: inline;
  width: 80%;
  padding-top: 40px;
  padding-bottom: 40px;
  outline:0;
  font-weight: 500;
  font-size: 1.3em;
  padding-left: 10%;
  padding-right: 10%;
}




.poem{
  display: block;
  text-align: center;
  margin:10px;
}
.poem > div{
  text-align: left;
  display: table;
  margin: 0 auto;
}

footer{
  background-color: #f6f6f6;
  padding-top: 2em;
  padding-bottom: 2em; 
  text-align:center;
}


